/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"

#include <string.h>

#include "pcm3060.h"


/* Audio Buffers */
#define AUDIO_BUFFER_SIZE 512
__attribute__((section(".RAM_D1"))) __attribute__((aligned(32))) volatile int32_t tx_buffer[AUDIO_BUFFER_SIZE];
__attribute__((section(".RAM_D1"))) __attribute__((aligned(32))) volatile int32_t rx_buffer[AUDIO_BUFFER_SIZE];

/* Private function prototypes */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_SPI4_Init(void);
static void MX_SAI1_Init(void);
void Disable_DCache_Safe(void);
//static void mySimpleWrite(void);

int main(void) {

	PWR->CR3 = (PWR->CR3 & ~(PWR_CR3_BYPASS | PWR_CR3_LDOEN));
    while(!(PWR->CSR1 & PWR_CSR1_ACTVOSRDY));

    PWR->D3CR |= PWR_D3CR_VOS; // Set to VOS0
    while (!(PWR->D3CR & PWR_D3CR_VOSRDY));

    // 1. Set the Power Voltage Scaling to Scale 1
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE1);

    // 2. Wait for the VOSRDY flag
	while (LL_PWR_IsActiveFlag_VOS() == 0);

    // 3. Enable the VOS0 (Scale 0) for boosted performance
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);

    // 4. Wait for the VOSRDY flag again
	while (LL_PWR_IsActiveFlag_VOS() == 0);


    // Use a simple loop to force the ECC to initialize
    for(int i=0; i < AUDIO_BUFFER_SIZE; i++) {
        rx_buffer[i] = 0;
        tx_buffer[i] = 0x12345678;
    }
    __DSB(); // Ensure writes are finished
    //SCB_CleanDCache_by_Addr((uint32_t*)rx_buffer, sizeof(rx_buffer));

    // memset((void*)rx_buffer, 0, sizeof(rx_buffer));
    // memset((void*)tx_buffer, 0, sizeof(tx_buffer));
    /* Enable I-Cache and D-Cache */
    //SCB_EnableICache();
   // SCB_EnableDCache();
    /* Set Priority Grouping */
    NVIC_SetPriorityGrouping(3); // NVIC_PRIORITYGROUP_4: 4 bits for pre-emption priority

    SystemClock_Config();

    /* Configure SysTick to 1ms for LL_mDelay */
    LL_Init1msTick(491520000);

    //uint32_t sai_clk = LL_RCC_GetSAIClockFreq(LL_RCC_SAI1_CLKSOURCE);
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_SPI4_Init();
    MX_SAI1_Init();

    /* Initialize PCM3060 via SPI4 */
    LL_GPIO_ResetOutputPin(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin); // Active Low Reset
    LL_mDelay(100);
    LL_GPIO_SetOutputPin(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin);
    LL_mDelay(10);
 //   mySimpleWrite();
    for(int i=0; i<AUDIO_BUFFER_SIZE; i++) {
        tx_buffer[i] = 0x12345678;
    }
    /* Start Audio Streaming via SAI DMA (TDM mode) */

    /* SAI1 Block B (RX) DMA Start */
    LL_DMA_SetMemoryAddress(DMA1, LL_DMA_STREAM_1, (uint32_t)rx_buffer);
    LL_DMA_SetPeriphAddress(DMA1, LL_DMA_STREAM_1, (uint32_t)&SAI1_Block_B->DR);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_1, AUDIO_BUFFER_SIZE);
    LL_DMA_EnableStream(DMA1, LL_DMA_STREAM_1);

    /* SAI1 Block A (TX) DMA Start */
    LL_DMA_SetMemoryAddress(DMA1, LL_DMA_STREAM_0, (uint32_t)tx_buffer);
    LL_DMA_SetPeriphAddress(DMA1, LL_DMA_STREAM_0, (uint32_t)&SAI1_Block_A->DR);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_0, AUDIO_BUFFER_SIZE);
    LL_DMA_EnableStream(DMA1, LL_DMA_STREAM_0);

    LL_mDelay(10);


    SAI1_Block_B->CR1 |= SAI_xCR1_DMAEN;
    SAI1_Block_B->CR1 |= SAI_xCR1_SAIEN;

    SAI1_Block_A->CR1 |= SAI_xCR1_DMAEN;
    SAI1_Block_A->CR1 |= SAI_xCR1_SAIEN;

    PCM3060_Init(SPI4);

    PCM3060_WriteReg(SPI4, 0x40, 0xC0);

    LL_mDelay(10);

    while (1) {
        /* Simple loopback: copy rx to tx */
        for (int i = 0; i < AUDIO_BUFFER_SIZE; i++) {
              //tx_buffer[i] = rx_buffer[i];
              int32_t raw_adc = (int32_t)rx_buffer[i];
              int32_t shifted_adc = raw_adc >> 8; // Shift out the 8-bit "padding" of a 24-bit sample
              int16_t monitor_val = (int16_t)(raw_adc >> 16);
              int32_t correctly_signed = (raw_adc << 8) >> 8;
        }
    }
}

static void MX_SAI1_Init(void) {
    // 1. Enable the Bus Clock (so you can talk to the registers)
    LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SAI1);

    // 1. Ensure the SAI blocks are disabled
    SAI1_Block_A->CR1 &= ~SAI_xCR1_SAIEN;
    SAI1_Block_B->CR1 &= ~SAI_xCR1_SAIEN;

    // 2. Perform the Peripheral Reset (Crucial to break the HSI lock)
    RCC->APB2RSTR |= RCC_APB2RSTR_SAI1RST;
    for(volatile int i=0; i<5000; i++); // Long delay for the bus
    RCC->APB2RSTR &= ~RCC_APB2RSTR_SAI1RST;

    //Ensure PLL1 is locked and DIVQ1EN is 1
    while(((!(RCC->CR & RCC_CR_PLL3RDY))));

    //saisel to pll3p

     RCC->D2CCIP1R &= ~(7U << 0);
     RCC->D2CCIP1R |= (2U << 0);

     //

    // 3. Re-verify the Mux (PLL3_P is 0x2, 0b010)
   // RCC->D2CCIP1R |= 0x2; // 010: PLL3_P
    // 4. Force the mux to a different, active clock first (e.g., PLL2_P or HSI)
   // MODIFY_REG(RCC->D2CCIP1R, RCC_D2CCIP1R_SAI1SEL, (1U << RCC_D2CCIP1R_SAI1SEL_Pos));
    //for(volatile int i=0; i<1000; i++);

    // 5. Now force it back to PLL1_Q (0x0)
   // MODIFY_REG(RCC->D2CCIP1R, RCC_D2CCIP1R_SAI1SEL, 0);
    // 6. Perform the Peripheral Reset
    // This "un-sticks" the internal state machine
//    RCC->APB2RSTR |= RCC_APB2RSTR_SAI1RST;
//    for(volatile int i=0; i<100; i++); // Short delay
//    RCC->APB2RSTR &= ~RCC_APB2RSTR_SAI1RST;

    // 3. Force the Clock Mux (again, just to be safe)
    //RCC->D2CCIP1R |= 0x2; // 010: PLL3_P
    // 3. Set the Kernel Clock Source (PLL1P)
    // Doing this after the reset ensures the Mux "takes" correctly
    LL_RCC_SetSAIClockSource(LL_RCC_SAI1_CLKSOURCE_PLL3P);

    while ((LL_APB2_GRP1_IsEnabledClock(LL_APB2_GRP1_PERIPH_SAI1))!=1);
    /* SAI1_Block_A: Transmit (Master) */
    SAI1_Block_A->CR1 = 0; // Disable

    // CR1: Asynchronous Master TX, I2S Free protocol, 24-bit
    SAI1_Block_A->CR1 = (0 << SAI_xCR1_MODE_Pos) | // 0: Master TX
                        (0 << SAI_xCR1_SYNCEN_Pos) | // 0: Asynchronous
                        (7 << SAI_xCR1_DS_Pos) | // 5: 24-bit
                        (0 << SAI_xCR1_LSBFIRST_Pos) | // 0: MSB first
                        (2 << SAI_xCR1_MCKDIV_Pos) |
                        SAI_xCR1_MCKEN; // Master clock enable

    // CR2: FIFO Threshold, MCLK Divider
    SAI1_Block_A->CR2 = (0 << SAI_xCR2_FTH_Pos); // 0: Empty


    // FRCR: Frame length = 64 (2 slots * 32 bits), Active frame length = 32 (FS high for 32 bits)
    SAI1_Block_A->FRCR = ((64 - 1) << SAI_xFRCR_FRL_Pos) |
                         ((32 - 1) << SAI_xFRCR_FSALL_Pos) |
                         SAI_xFRCR_FSDEF | // FS is channel identification
                         (0 << SAI_xFRCR_FSPOL_Pos) | // 0: FS active low (I2S standard)
                            (SAI_xFRCR_FSOFF); // FS 1 bit before data

    // // SLOTR: 2 slots, each 32-bit, slots 0 and 1 active
    // SAI1_Block_A->SLOTR = (0 << SAI_xSLOTR_FBOFF_Pos) |
    //                       (2 << SAI_xSLOTR_SLOTSZ_Pos) | // 2: 32-bit
    //                       ((2 - 1) << SAI_xSLOTR_NBSLOT_Pos) |
    //                       SAI_xSLOTR_SLOTEN; // Enable all slots (or at least first 2)
    // Enable exactly Slot 0 and Slot 1
    SAI1_Block_A->SLOTR = (0 << SAI_xSLOTR_FBOFF_Pos) |
                          (2 << SAI_xSLOTR_SLOTSZ_Pos) | // 32-bit
                          (1 << SAI_xSLOTR_NBSLOT_Pos) | // 2 slots (N-1)
                          (0x3U << 16);                 // SLOTEN[1:0] bits

    /* SAI1_Block_B: Receive (Slave) */
    SAI1_Block_B->CR1 = 0; // Disable

    // CR1: Synchronous Slave RX, 24-bit
    SAI1_Block_B->CR1 = (3 << SAI_xCR1_MODE_Pos) | // 3: Slave RX
                        (1 << SAI_xCR1_SYNCEN_Pos) | // 1: Synchronous with other block
                        (7 << SAI_xCR1_DS_Pos); // 5: 24-bit

    SAI1_Block_B->FRCR = SAI1_Block_A->FRCR;

    SAI1_Block_B->SLOTR = SAI1_Block_A->SLOTR;
}

static void MX_SPI4_Init(void) {

    //this seems the order for ssm/master config without triggering modf
    // SPI4->IFCR |= SPI_IFCR_MODFC;       // 1. Clear any old fault
    // SPI4->CFG2 |= SPI_CFG2_SP_0;
    //
    // SPI4->CR1  |= SPI_CR1_SSI;          // 2. Force internal signal HIGH
    // SPI4->CFG2 |= SPI_CFG2_SSM;         // 3. Enable Software Management
    // SPI4->CFG2 |= SPI_CFG2_MASTER;      // 4. NOW set Master mode
    // SPI4->CR1  |= SPI_CR1_SPE;          // 5. Enable SPI
    LL_SPI_Disable(SPI4);
    SPI4->IFCR = 0xFFFFFFFF;

    LL_SPI_SetNSSMode(SPI4, LL_SPI_NSS_SOFT);
    LL_SPI_SetInternalSSLevel(SPI4, LL_SPI_SS_LEVEL_HIGH);

    LL_SPI_SetMode(SPI4, LL_SPI_MODE_MASTER);
    LL_SPI_SetStandard(SPI4, LL_SPI_PROTOCOL_MOTOROLA);
    LL_SPI_SetTransferDirection(SPI4, LL_SPI_SIMPLEX_TX);
    LL_SPI_SetDataWidth(SPI4, LL_SPI_DATAWIDTH_8BIT);
    LL_SPI_SetClockPolarity(SPI4, LL_SPI_POLARITY_LOW);
    LL_SPI_SetClockPhase(SPI4, LL_SPI_PHASE_1EDGE);
    LL_SPI_SetNSSMode(SPI4, LL_SPI_NSS_SOFT);
    LL_SPI_SetBaudRatePrescaler(SPI4, LL_SPI_BAUDRATEPRESCALER_DIV64);
    LL_SPI_SetTransferBitOrder(SPI4, LL_SPI_MSB_FIRST);
    LL_SPI_SetFIFOThreshold(SPI4, LL_SPI_FIFO_TH_01DATA);
    LL_SPI_Enable(SPI4);
    LL_SPI_ClearFlag_MODF(SPI4);
    //toggle cs
    LL_GPIO_ResetOutputPin(GPIOD, LL_GPIO_PIN_14);  // CS low
    LL_SPI_TransmitData8(SPI4, 0x0);
    LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);    // CS high
    SPI4->IFCR |= SPI_IFCR_MODFC;       // 1. Clear any old fault
    //SPI4->CFG2 |= SPI_CFG2_SP_0;

    SPI4->CR1  |= SPI_CR1_SSI;          // 2. Force internal signal HIGH
    SPI4->CFG2 |= SPI_CFG2_SSM;         // 3. Enable Software Management
    SPI4->CFG2 |= SPI_CFG2_MASTER;      // 4. NOW set Master mode
    SPI4->CR1  |= SPI_CR1_SPE;          // 5. Enable SPI
}

static void MX_DMA_Init(void) {
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_DMA1);

    /* SAI1_A DMA (TX) */
    LL_DMA_ConfigTransfer(DMA1, LL_DMA_STREAM_0, LL_DMA_DIRECTION_MEMORY_TO_PERIPH);
    //LL_DMA_ConfigAddresses(DMA1, LL_DMA_STREAM_0, 0, 0, LL_DMA_DIRECTION_MEMORY_TO_PERIPH);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_0, AUDIO_BUFFER_SIZE);
    LL_DMA_SetPeriphRequest(DMA1, LL_DMA_STREAM_0, LL_DMAMUX1_REQ_SAI1_A);
    LL_DMA_ConfigTransfer(DMA1, LL_DMA_STREAM_0, LL_DMA_DIRECTION_MEMORY_TO_PERIPH |
                          LL_DMA_MODE_CIRCULAR | LL_DMA_PERIPH_NOINCREMENT |
                          LL_DMA_MEMORY_INCREMENT | LL_DMA_PDATAALIGN_WORD |
                          LL_DMA_MDATAALIGN_WORD | LL_DMA_PRIORITY_HIGH);
    LL_DMA_EnableFifoMode(DMA1, LL_DMA_STREAM_0);
    LL_DMA_SetFIFOThreshold(DMA1, LL_DMA_STREAM_0, LL_DMA_FIFOTHRESHOLD_1_2);

    LL_DMA_SetMemorySize(DMA1, LL_DMA_STREAM_0, LL_DMA_MDATAALIGN_WORD);
    LL_DMA_SetPeriphSize(DMA1, LL_DMA_STREAM_0, LL_DMA_PDATAALIGN_WORD);
    /* Enable interrupts for TX */
   // LL_DMA_EnableIT_TC(DMA1, LL_DMA_STREAM_0);
   // LL_DMA_EnableIT_HT(DMA1, LL_DMA_STREAM_0);

    /* SAI1_B DMA (RX) */
    LL_DMA_ConfigTransfer(DMA1, LL_DMA_STREAM_1, LL_DMA_DIRECTION_PERIPH_TO_MEMORY);
    //LL_DMA_ConfigAddresses(DMA1, LL_DMA_STREAM_1, 0, 0, LL_DMA_DIRECTION_PERIPH_TO_MEMORY);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_1, AUDIO_BUFFER_SIZE);
    LL_DMA_SetPeriphRequest(DMA1, LL_DMA_STREAM_1, LL_DMAMUX1_REQ_SAI1_B);
    LL_DMA_ConfigTransfer(DMA1, LL_DMA_STREAM_1, LL_DMA_DIRECTION_PERIPH_TO_MEMORY |
                          LL_DMA_MODE_CIRCULAR | LL_DMA_PERIPH_NOINCREMENT |
                          LL_DMA_MEMORY_INCREMENT | LL_DMA_PDATAALIGN_WORD |
                          LL_DMA_MDATAALIGN_WORD | LL_DMA_PRIORITY_HIGH);
    LL_DMA_EnableFifoMode(DMA1, LL_DMA_STREAM_1);
    LL_DMA_SetFIFOThreshold(DMA1, LL_DMA_STREAM_1, LL_DMA_FIFOTHRESHOLD_1_2);

    LL_DMA_SetMemorySize(DMA1, LL_DMA_STREAM_1, LL_DMA_MDATAALIGN_WORD);
    LL_DMA_SetPeriphSize(DMA1, LL_DMA_STREAM_1, LL_DMA_PDATAALIGN_WORD);
    /* Enable interrupts for RX */
   // LL_DMA_EnableIT_TC(DMA1, LL_DMA_STREAM_1);
   // LL_DMA_EnableIT_HT(DMA1, LL_DMA_STREAM_1);

    /* NVIC configuration for DMA interrupts */
    NVIC_SetPriority(DMA1_Stream0_IRQn, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 0));
    NVIC_EnableIRQ(DMA1_Stream0_IRQn);
    NVIC_SetPriority(DMA1_Stream1_IRQn, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 0));
    NVIC_EnableIRQ(DMA1_Stream1_IRQn);
}

static void MX_GPIO_Init(void) {
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOA);
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOD);
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOE);
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOF);

    /* RST pin. PE15 */
    LL_GPIO_SetPinMode(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_MODE_OUTPUT);
    LL_GPIO_SetPinSpeed(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_SPEED_FREQ_LOW);
    LL_GPIO_SetPinPull(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_PULL_NO);
    LL_GPIO_SetPinOutputType(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetOutputPin(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin); // High: Inactive

    /* MODE Pin. PE11 */
    //ALSO WE NEED TO PULL THIS HIGH EXTERNALLY. SO 3060 FINDS IT IN CORRECT MODE AT BOOT
    LL_GPIO_SetPinMode(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_MODE_OUTPUT);
    LL_GPIO_SetPinSpeed(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_SPEED_FREQ_LOW);
    LL_GPIO_SetPinPull(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_PULL_UP);
    LL_GPIO_SetPinOutputType(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetOutputPin(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin); // High: Inactive


    /* SPI4 GPIO: PE12 (SCK), PE14 (MOSI) */
    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_12, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_8_15(GPIOE, LL_GPIO_PIN_12, LL_GPIO_AF_5);
    LL_GPIO_SetPinOutputType(GPIOE, LL_GPIO_PIN_12, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_12, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_14, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_8_15(GPIOE, LL_GPIO_PIN_14, LL_GPIO_AF_5);
    LL_GPIO_SetPinOutputType(GPIOE, LL_GPIO_PIN_14, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_14, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    /* SPI1 CS: PD14 */
    LL_GPIO_SetPinMode(GPIOD, LL_GPIO_PIN_14, LL_GPIO_MODE_OUTPUT);
    LL_GPIO_SetPinSpeed(GPIOD, LL_GPIO_PIN_14, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinOutputType(GPIOD, LL_GPIO_PIN_14, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinPull(GPIOD, LL_GPIO_PIN_14, LL_GPIO_PULL_UP); //or modf persists even tho we are using software nss.
    LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);

    /* SAI1 GPIO: PE2 (MCLK), PE4 (FS), PE5 (SCK), PE6 (SD_A), PE3 (SD_B) */
    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_2, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_2, LL_GPIO_SPEED_FREQ_VERY_HIGH);


    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_3, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_3, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_3, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    GPIOE->PUPDR &= ~(3U << (3 * 2));
    GPIOE->PUPDR |= (0U << (3 * 2)); // 00: No Pull-up
    // 1. Enable GPIOE Clock
//    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOEEN;
//
//    // 2. Set PE3 as INPUT (00)
//    GPIOE->MODER &= ~(3U << (3 * 2));
//
//    // 3. Force a PULL-UP (01)
//    GPIOE->PUPDR &= ~(3U << (3 * 2));
//    GPIOE->PUPDR |=  (1U << (3 * 2));
//
//    // 4. Ensure no other AF is claiming it (set to 0)
//    GPIOE->AFR[0] &= ~(0x0F << (3 * 4));

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_4, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_4, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_4, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_5, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_5, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_5, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_6, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_6, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_6, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    //disabling contentious pe3 af6 pin. enable as op
    LL_GPIO_SetPinMode(GPIOF, LL_GPIO_PIN_6, LL_GPIO_MODE_OUTPUT);

}

void SystemClock_Config(void) {
	/* Enable HSE */
    LL_RCC_HSE_Enable();
    while(LL_RCC_HSE_IsReady() != 1);

    LL_FLASH_SetLatency(LL_FLASH_LATENCY_4);
    while(LL_FLASH_GetLatency() != LL_FLASH_LATENCY_4);
    LL_RCC_SetAHBPrescaler(LL_RCC_AHB_DIV_2);
	LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_2);
	LL_RCC_SetAPB2Prescaler(LL_RCC_APB2_DIV_2);
	LL_RCC_SetAPB3Prescaler(LL_RCC_APB3_DIV_2);
	LL_RCC_SetAPB4Prescaler(LL_RCC_APB4_DIV_2);

    /* PLL3 Configuration for audio Clock and 98.304MHz PLL1Q */
    /* HSE = 25MHz.
       M = 5 -> 5MHz input to PLL.
       N = 98.304 -> VCO = 5 * 98.304 = 491.52 MHz.
       P = 1 -> CPU = 491.52 MHz (H723 limit is 550MHz).
       Q = 5 -> PLL1Q = 491.52 / 5 = 98.304 MHz.
       FRACN = 0.304 * 8192 = 2490.
    */
	while ((LL_RCC_HSE_IsReady()!=1));

    LL_RCC_PLL_SetSource(LL_RCC_PLLSOURCE_HSE);


    LL_RCC_PLL3_Disable();
    while(LL_RCC_PLL3_IsReady()); // wait for it to stop
    LL_RCC_PLL3_SetM(1);
    LL_RCC_PLL3_SetN(61);
    LL_RCC_PLL3_SetP(10); // 49.152MHz / 2 = 24.576MHz MCLK

    LL_RCC_PLL3_SetFRACN(3604);
    LL_RCC_PLL3FRACN_Enable();
    LL_RCC_PLL3_Enable();
    while(!LL_RCC_PLL3_IsReady());

//    LL_RCC_PLL3_SetFRACN(3604);
//    LL_RCC_PLL3FRACN_Enable();

    //LL_RCC_PLL3_SetQ(1);
    //LL_RCC_PLL3_SetR(2);


    LL_RCC_PLL3_SetVCOInputRange(LL_RCC_PLLINPUTRANGE_4_8);
    LL_RCC_PLL3_SetVCOOutputRange(LL_RCC_PLLVCORANGE_WIDE);

    LL_RCC_PLL3P_Enable();
    //LL_RCC_PLL3Q_Enable();
    while (LL_RCC_PLL3P_IsEnabled()!=1);

    __DSB();
    LL_RCC_PLL3_Enable();
    while(LL_RCC_PLL3_IsReady() != 1);
    // 1. Wait for PLL3RDY (Bit 28 in RCC->CR)
    while(!(RCC->CR & RCC_CR_PLL3RDY));

    // 2. Perform the Hard Reset to break the HSI lock
    RCC->APB2RSTR |= RCC_APB2RSTR_SAI1RST;
    for(volatile int i=0; i<5000; i++);
    RCC->APB2RSTR &= ~RCC_APB2RSTR_SAI1RST;

    // 3. Force the Mux to PLL3_P (Value 0x3 or 0x2 depending on H7 rev)
   // LL_RCC_SetSAIClockSource(LL_RCC_SAI1_CLKSOURCE_PLL3P);
    // Force the SAI to "Forget" the HSI (Peripheral Reset)
    // This is the ONLY way to force the internal clock mux to re-sample
    RCC->APB2RSTR |= RCC_APB2RSTR_SAI1RST;
    for(volatile int i=0; i<5000; i++); // Wait longer to ensure it clears
    RCC->APB2RSTR &= ~RCC_APB2RSTR_SAI1RST;

    //saisel to pll3p
    RCC->D2CCIP1R &= ~(7U << 0);
    RCC->D2CCIP1R |= (2U << 0);


    /* PLL1 Configuration for System Clock and 98.304MHz PLL3Q */
       /* HSE = 25MHz.
          M = 5 -> 5MHz input to PLL.
          N = 98.304 -> VCO = 5 * 98.304 = 491.52 MHz.
          P = 1 -> CPU = 491.52 MHz (H723 limit is 550MHz).
          Q = 5 -> PLL1Q = 491.52 / 5 = 98.304 MHz.
          FRACN = 0.304 * 8192 = 2490.
       */
    LL_RCC_PLL1_SetM(1);
    LL_RCC_PLL1_SetN(123);

    LL_RCC_PLL1_SetP(2);
    LL_RCC_PLL1_SetQ(40);

    LL_RCC_PLL1_SetVCOInputRange(LL_RCC_PLLINPUTRANGE_4_8);
    LL_RCC_PLL1_SetVCOOutputRange(LL_RCC_PLLVCORANGE_WIDE);

    LL_RCC_PLL1P_Enable();
    LL_RCC_PLL1Q_Enable();
    while (LL_RCC_PLL1Q_IsEnabled()!=1);

    __DSB();
    LL_RCC_PLL1_Enable();
    while(LL_RCC_PLL1_IsReady() != 1);

    LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL1);
    while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL1);

    // kernel clock source first
    RCC->D2CCIP1R &= ~RCC_D2CCIP1R_SPI45SEL; //0b000 =apb2
    RCC->D2CCIP1R |= (0x3 << RCC_D2CCIP1R_SPI45SEL_Pos);  // HSE
    __NOP();
    RCC->APB2ENR |= RCC_APB2ENR_SPI4EN;
    __NOP();
    (void)RCC->APB2ENR;  // dummy read to ensure clock is active

    // verify immediately
    if (!(RCC->APB2ENR & RCC_APB2ENR_SPI4EN)) {
        // trap here if still not set
        while(1);
    }
    // // Enable SRAM1, SRAM2 clocks (D2 Domain)
    // LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_D2SRAM1 |
    //                          LL_AHB2_GRP1_PERIPH_D2SRAM2);

    RCC->AHB2ENR |= (RCC_AHB2ENR_SRAM1EN | RCC_AHB2ENR_SRAM2EN);
    // Short delay to ensure clock is stable before access
    (void)RCC->AHB2ENR;

}


//void Disable_DCache_Safe(void) {
//    // 1. Clean and Invalidate: Force all cached data into AXI SRAM (0x24000000)
//    // This ensures your stack and variables are actually in RAM.
//    SCB_CleanInvalidateDCache();
//
//    // 2. Data Synchronization Barrier: Wait for all memory writes to finish
//    __DSB();
//
//    // 3. Disable the D-Cache bit in the System Control Block
//    SCB->CCR &= ~(uint32_t)SCB_CCR_DC_Msk;
//
//    // 4. Instruction Synchronization Barrier: Flush the CPU pipeline
//    __DSB();
//    __ISB();
//}


//
// static void mySimpleWrite(void){
//     // // CS low
//     LL_GPIO_ResetOutputPin(GPIOD, LL_GPIO_PIN_14);
//     // write both bytes
//     while (!(SPI4->SR & SPI_SR_TXP));
//     *(volatile uint8_t *)&SPI4->TXDR = 0xAA;
//     while (!(SPI4->SR & SPI_SR_TXP));
//     *(volatile uint8_t *)&SPI4->TXDR = 0x55;
//     // start
//     SPI4->CR1 |= SPI_CR1_CSTART;
//     __DSB();
//     __NOP();
//     //CS high
//     LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);
// }

void Error_Handler(void) {
    while (1);
}
