/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
#include "pcm3060.h"


/* Audio Buffers */
#define AUDIO_BUFFER_SIZE 512
__attribute__((aligned(32))) volatile int32_t tx_buffer[AUDIO_BUFFER_SIZE];
__attribute__((aligned(32))) volatile int32_t rx_buffer[AUDIO_BUFFER_SIZE];

/* Private function prototypes */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_SPI4_Init(void);
static void MX_SAI1_Init(void);
static void mySimpleWrite(void);

int main(void) {
    /* Enable I-Cache and D-Cache */
    SCB_EnableICache();
    SCB_EnableDCache();

    /* Set Priority Grouping */
    NVIC_SetPriorityGrouping(3); // NVIC_PRIORITYGROUP_4: 4 bits for pre-emption priority

    /* System initialization */
    SystemClock_Config();
    // PWR->CR3 |= PWR_CR3_LDOEN;
    // while(!(PWR->CSR1 & PWR_CSR1_ACTVOSRDY));

    /* Configure SysTick to 1ms for LL_mDelay */
    LL_Init1msTick(491520000);

    //uint32_t sai_clk = LL_RCC_GetSAIClockFreq(LL_RCC_SAI1_CLKSOURCE);
    MX_GPIO_Init();
    // // disable
    // // reset SPI4 via RCC
    // RCC->APB2RSTR |=  RCC_APB2RSTR_SPI4RST;
    // __NOP();
    // RCC->APB2RSTR &= ~RCC_APB2RSTR_SPI4RST;
    // __NOP();
    //
    // // re-enable clock
    // RCC->APB2ENR |= RCC_APB2ENR_SPI4EN;
    // __NOP();
    // (void)RCC->APB2ENR;
    // write MASTER alone first
    // SPI4->IFCR |= SPI_IFCR_MODFC;       // 1. Clear any old fault
    // SPI4->CFG2 |= SPI_CFG2_SP_0;
    //
    // SPI4->CR1  |= SPI_CR1_SSI;          // 2. Force internal signal HIGH
    // SPI4->CFG2 |= SPI_CFG2_SSM;         // 3. Enable Software Management
    // SPI4->CFG2 |= SPI_CFG2_MASTER;      // 4. NOW set Master mode
    // SPI4->CR1  |= SPI_CR1_SPE;          // 5. Enable SPI
    //
    // // SPI4->CFG2 |= SPI_CFG2_SP_0;
    // // SPI4->CR1 |= SPI_CR1_SSI;
    // // SPI4->CFG2 |= SPI_CFG2_SSM;
    // // SPI4->CFG2 |= SPI_CFG2_SSOE;
    // // __NOP();
    // // SPI4->CFG2 = SPI_CFG2_MASTER;
    // // SPI4->CR1 |= SPI_CR1_SPE;
    // // __NOP();
    // SPI4->CR1 |= SPI_CR1_CSTART;
    // __NOP();
    // uint32_t cfg2_check = SPI4->CFG2;  // breakpoint - does MASTER set in isolation?
    // uint32_t dummy = 0;
    //
    // uint32_t apb2enr_check = RCC->APB2ENR;  // breakpoint here
    // // is bit 13 set?
    //
    // // now write CFG2 to a freshly reset peripheral
    // SPI4->CFG2 = SPI_CFG2_MASTER
    //            | SPI_CFG2_SSM
    //            | SPI_CFG2_AFCNTR
    //            | SPI_CFG2_SSOM;
    //
    // SPI4->CR1 &= ~SPI_CR1_SPE;
    // SPI4->IFCR = 0xFFFFFFFF;
    // // CFG1: DSIZE=7 (8bit), FTHLV=0 (1 data), MBR=5 (div64)
    // SPI4->CFG1 = (5 << SPI_CFG1_MBR_Pos) | (7 << SPI_CFG1_DSIZE_Pos);
    // // CFG2: MASTER, SSM, full duplex, Motorola, CPOL=0, CPHA=0, MSB first
    // SPI4->CFG2 = SPI_CFG2_MASTER | SPI_CFG2_SSM | SPI_CFG2_AFCNTR | SPI_CFG2_SSOM;
    // // TSIZE=2
    // SPI4->CR2 = 1;
    // // SSI high
    // SPI4->CR1 = SPI_CR1_SSI;
    // __DSB();
    // (void)SPI4->CR1;
    // __NOP(); __NOP(); __NOP(); __NOP();  // let SPE settle
    // // enable
    // SPI4->CR1 |= SPI_CR1_SPE ;
    // __DSB();
    // (void)SPI4->CR1;
    //
    //
    // uint32_t cr2_check = SPI4->CR2;  // should be 1, breakpoint here
    //
    // *(volatile uint8_t *)&SPI4->TXDR = 0xAA;
    // SPI4->CR1 |= SPI_CR1_CSTART;
    //
    // // verify MODF is clear before proceeding
    // if (SPI4->SR & SPI_SR_MODF) {
    //     SPI4->IFCR |= SPI_IFCR_MODFC;  // clear it
    //     SPI4->CR1  |= SPI_CR1_SPE;     // re-enable
    // }
    //
    //
    // SPI4->CR2 = 1;  // re-set TSIZE as SPE cycle may clear it
    //
    // // CS low
    // LL_GPIO_ResetOutputPin(GPIOD, LL_GPIO_PIN_14);
    // __DSB();
    // __NOP(); __NOP(); __NOP(); __NOP();  // let SPE settle
    //
    // // write both bytes
    // while (!(SPI4->SR & SPI_SR_TXP));
    // *(volatile uint8_t *)&SPI4->TXDR = 0xAA;
    // while (!(SPI4->SR & SPI_SR_TXP));
    // *(volatile uint8_t *)&SPI4->TXDR = 0x55;
    // // start
    // SPI4->CR1 |= SPI_CR1_CSTART;
    // __DSB();
    // __NOP();
    // uint32_t cr1  = SPI4->CR1;
    // uint32_t cr2  = SPI4->CR2;
    // uint32_t cfg1 = SPI4->CFG1;
    // uint32_t cfg2 = SPI4->CFG2;
    // uint32_t sr   = SPI4->SR;
    // // breakpoint here
    // dummy = 0;
    // // put breakpoint here and read sr_after_cstart
    //
    // while (!(SPI4->SR & SPI_SR_EOT));
    // SPI4->IFCR |= SPI_IFCR_EOTC;

    // CS high
   // LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);

    MX_DMA_Init();
    MX_SPI4_Init();
    MX_SAI1_Init();

    /* Initialize PCM3060 via SPI4 */
    LL_GPIO_ResetOutputPin(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin); // Active Low Reset
    LL_mDelay(10);
    LL_GPIO_SetOutputPin(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin);
    LL_mDelay(10);
    mySimpleWrite();

    PCM3060_Init(SPI4);
    /* Start Audio Streaming via SAI DMA (TDM mode) */

    /* SAI1 Block A (TX) DMA Start */
    LL_DMA_SetMemoryAddress(DMA1, LL_DMA_STREAM_0, (uint32_t)tx_buffer);
    LL_DMA_SetPeriphAddress(DMA1, LL_DMA_STREAM_0, (uint32_t)&SAI1_Block_A->DR);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_0, AUDIO_BUFFER_SIZE);
    LL_DMA_EnableStream(DMA1, LL_DMA_STREAM_0);

    SAI1_Block_A->CR1 |= SAI_xCR1_DMAEN;
    SAI1_Block_A->CR1 |= SAI_xCR1_SAIEN;

    /* SAI1 Block B (RX) DMA Start */
    LL_DMA_SetMemoryAddress(DMA1, LL_DMA_STREAM_1, (uint32_t)rx_buffer);
    LL_DMA_SetPeriphAddress(DMA1, LL_DMA_STREAM_1, (uint32_t)&SAI1_Block_B->DR);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_1, AUDIO_BUFFER_SIZE);
    LL_DMA_EnableStream(DMA1, LL_DMA_STREAM_1);

    SAI1_Block_B->CR1 |= SAI_xCR1_DMAEN;
    SAI1_Block_B->CR1 |= SAI_xCR1_SAIEN;

    while (1) {
        /* Simple loopback: copy rx to tx */
        for (int i = 0; i < AUDIO_BUFFER_SIZE; i++) {
            tx_buffer[i] = rx_buffer[i];
        }
    }
}

static void MX_SAI1_Init(void) {
    LL_RCC_SetSAIClockSource(LL_RCC_SAI1_CLKSOURCE_PLL1Q);
    LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SAI1);

    /* SAI1_Block_A: Transmit (Master) */
    SAI1_Block_A->CR1 = 0; // Disable

    // CR1: Asynchronous Master TX, I2S Free protocol, 24-bit
    SAI1_Block_A->CR1 = (0 << SAI_xCR1_MODE_Pos) | // 0: Master TX
                        (0 << SAI_xCR1_SYNCEN_Pos) | // 0: Asynchronous
                        (5 << SAI_xCR1_DS_Pos) | // 5: 24-bit
                        (0 << SAI_xCR1_LSBFIRST_Pos) | // 0: MSB first
                        SAI_xCR1_MCKEN; // Master clock enable

    // CR2: FIFO Threshold, MCLK Divider
    SAI1_Block_A->CR2 = (0 << SAI_xCR2_FTH_Pos) | // 0: Empty
                        (4 << 20); // MCKDIV = 4 (for 96kHz with 98.304MHz SAI_CLK)

    // FRCR: Frame length = 64 (2 slots * 32 bits), Active frame length = 32 (FS high for 32 bits)
    SAI1_Block_A->FRCR = ((64 - 1) << SAI_xFRCR_FRL_Pos) |
                         ((32 - 1) << SAI_xFRCR_FSALL_Pos) |
                         SAI_xFRCR_FSDEF | // FS is channel identification
                         (0 << SAI_xFRCR_FSPOL_Pos) | // 0: FS active low (I2S standard)
                         SAI_xFRCR_FSOFF; // FS 1 bit before data

    // SLOTR: 2 slots, each 32-bit, slots 0 and 1 active
    SAI1_Block_A->SLOTR = (0 << SAI_xSLOTR_FBOFF_Pos) |
                          (2 << SAI_xSLOTR_SLOTSZ_Pos) | // 2: 32-bit
                          ((2 - 1) << SAI_xSLOTR_NBSLOT_Pos) |
                          SAI_xSLOTR_SLOTEN; // Enable all slots (or at least first 2)

    /* SAI1_Block_B: Receive (Slave) */
    SAI1_Block_B->CR1 = 0; // Disable

    // CR1: Synchronous Slave RX, 24-bit
    SAI1_Block_B->CR1 = (3 << SAI_xCR1_MODE_Pos) | // 3: Slave RX
                        (1 << SAI_xCR1_SYNCEN_Pos) | // 1: Synchronous with other block
                        (5 << SAI_xCR1_DS_Pos); // 5: 24-bit

    SAI1_Block_B->FRCR = SAI1_Block_A->FRCR;
    SAI1_Block_B->SLOTR = SAI1_Block_A->SLOTR;
}

static void MX_SPI4_Init(void) {

    //this seems the order for ssm/master config without triggering modf
    // SPI4->IFCR |= SPI_IFCR_MODFC;       // 1. Clear any old fault
    // SPI4->CFG2 |= SPI_CFG2_SP_0;
    //
    // SPI4->CR1  |= SPI_CR1_SSI;          // 2. Force internal signal HIGH
    // SPI4->CFG2 |= SPI_CFG2_SSM;         // 3. Enable Software Management
    // SPI4->CFG2 |= SPI_CFG2_MASTER;      // 4. NOW set Master mode
    // SPI4->CR1  |= SPI_CR1_SPE;          // 5. Enable SPI
    LL_SPI_Disable(SPI4);
    SPI4->IFCR = 0xFFFFFFFF;

    LL_SPI_SetNSSMode(SPI4, LL_SPI_NSS_SOFT);
    LL_SPI_SetInternalSSLevel(SPI4, LL_SPI_SS_LEVEL_HIGH);

    LL_SPI_SetMode(SPI4, LL_SPI_MODE_MASTER);
    LL_SPI_SetStandard(SPI4, LL_SPI_PROTOCOL_MOTOROLA);
    LL_SPI_SetTransferDirection(SPI4, LL_SPI_SIMPLEX_TX);
    LL_SPI_SetDataWidth(SPI4, LL_SPI_DATAWIDTH_8BIT);
    LL_SPI_SetClockPolarity(SPI4, LL_SPI_POLARITY_LOW);
    LL_SPI_SetClockPhase(SPI4, LL_SPI_PHASE_1EDGE);
    LL_SPI_SetNSSMode(SPI4, LL_SPI_NSS_SOFT);
    LL_SPI_SetBaudRatePrescaler(SPI4, LL_SPI_BAUDRATEPRESCALER_DIV64);
    LL_SPI_SetTransferBitOrder(SPI4, LL_SPI_MSB_FIRST);
    LL_SPI_SetFIFOThreshold(SPI4, LL_SPI_FIFO_TH_01DATA);
    LL_SPI_Enable(SPI4);
    LL_SPI_ClearFlag_MODF(SPI4);
    //toggle cs
    LL_GPIO_ResetOutputPin(GPIOD, LL_GPIO_PIN_14);  // CS low
    LL_SPI_TransmitData8(SPI4, 0x0);
    LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);    // CS high
    SPI4->IFCR |= SPI_IFCR_MODFC;       // 1. Clear any old fault
    //SPI4->CFG2 |= SPI_CFG2_SP_0;

    SPI4->CR1  |= SPI_CR1_SSI;          // 2. Force internal signal HIGH
    SPI4->CFG2 |= SPI_CFG2_SSM;         // 3. Enable Software Management
    SPI4->CFG2 |= SPI_CFG2_MASTER;      // 4. NOW set Master mode
    SPI4->CR1  |= SPI_CR1_SPE;          // 5. Enable SPI
}

static void MX_DMA_Init(void) {
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_DMA1);

    /* SAI1_A DMA (TX) */
    LL_DMA_ConfigAddresses(DMA1, LL_DMA_STREAM_0, 0, 0, LL_DMA_DIRECTION_MEMORY_TO_PERIPH);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_0, AUDIO_BUFFER_SIZE);
    LL_DMA_SetPeriphRequest(DMA1, LL_DMA_STREAM_0, LL_DMAMUX1_REQ_SAI1_A);
    LL_DMA_ConfigTransfer(DMA1, LL_DMA_STREAM_0, LL_DMA_DIRECTION_MEMORY_TO_PERIPH |
                          LL_DMA_MODE_CIRCULAR | LL_DMA_PERIPH_NOINCREMENT |
                          LL_DMA_MEMORY_INCREMENT | LL_DMA_PDATAALIGN_WORD |
                          LL_DMA_MDATAALIGN_WORD | LL_DMA_PRIORITY_HIGH);
    LL_DMA_EnableFifoMode(DMA1, LL_DMA_STREAM_0);
    LL_DMA_SetFIFOThreshold(DMA1, LL_DMA_STREAM_0, LL_DMA_FIFOTHRESHOLD_1_2);

    /* Enable interrupts for TX */
    LL_DMA_EnableIT_TC(DMA1, LL_DMA_STREAM_0);
    LL_DMA_EnableIT_HT(DMA1, LL_DMA_STREAM_0);

    /* SAI1_B DMA (RX) */
    LL_DMA_ConfigAddresses(DMA1, LL_DMA_STREAM_1, 0, 0, LL_DMA_DIRECTION_PERIPH_TO_MEMORY);
    LL_DMA_SetDataLength(DMA1, LL_DMA_STREAM_1, AUDIO_BUFFER_SIZE);
    LL_DMA_SetPeriphRequest(DMA1, LL_DMA_STREAM_1, LL_DMAMUX1_REQ_SAI1_B);
    LL_DMA_ConfigTransfer(DMA1, LL_DMA_STREAM_1, LL_DMA_DIRECTION_PERIPH_TO_MEMORY |
                          LL_DMA_MODE_CIRCULAR | LL_DMA_PERIPH_NOINCREMENT |
                          LL_DMA_MEMORY_INCREMENT | LL_DMA_PDATAALIGN_WORD |
                          LL_DMA_MDATAALIGN_WORD | LL_DMA_PRIORITY_HIGH);
    LL_DMA_EnableFifoMode(DMA1, LL_DMA_STREAM_1);
    LL_DMA_SetFIFOThreshold(DMA1, LL_DMA_STREAM_1, LL_DMA_FIFOTHRESHOLD_1_2);

    /* Enable interrupts for RX */
    LL_DMA_EnableIT_TC(DMA1, LL_DMA_STREAM_1);
    LL_DMA_EnableIT_HT(DMA1, LL_DMA_STREAM_1);

    /* NVIC configuration for DMA interrupts */
    NVIC_SetPriority(DMA1_Stream0_IRQn, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 0));
    NVIC_EnableIRQ(DMA1_Stream0_IRQn);
    NVIC_SetPriority(DMA1_Stream1_IRQn, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), 0, 0));
    NVIC_EnableIRQ(DMA1_Stream1_IRQn);
}

static void MX_GPIO_Init(void) {
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOA);
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOD);
    LL_AHB4_GRP1_EnableClock(LL_AHB4_GRP1_PERIPH_GPIOE);


    /* RST pin. PE15 */
    LL_GPIO_SetPinMode(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_MODE_OUTPUT);
    LL_GPIO_SetPinSpeed(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_SPEED_FREQ_LOW);
    LL_GPIO_SetPinPull(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_PULL_NO);
    LL_GPIO_SetPinOutputType(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetOutputPin(PCM3060_RST_GPIO_Port, PCM3060_RST_Pin); // High: Inactive

    /* MODE Pin. PE11 */
    //ALSO WE NEED TO PULL THIS HIGH EXTERNALLY. SO 3060 FINDS IT IN CORRECT MODE AT BOOT
    LL_GPIO_SetPinMode(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_MODE_ANALOG);
    LL_GPIO_SetPinSpeed(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_SPEED_FREQ_LOW);
    LL_GPIO_SetPinPull(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_PULL_UP);
    LL_GPIO_SetPinOutputType(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetOutputPin(PCM3060_MODE_GPIO_Port, PCM3060_MODE_Pin); // High: Inactive


    /* SPI4 GPIO: PE12 (SCK), PE14 (MOSI) */
    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_12, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_8_15(GPIOE, LL_GPIO_PIN_12, LL_GPIO_AF_5);
    LL_GPIO_SetPinOutputType(GPIOE, LL_GPIO_PIN_12, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_12, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_14, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_8_15(GPIOE, LL_GPIO_PIN_14, LL_GPIO_AF_5);
    LL_GPIO_SetPinOutputType(GPIOE, LL_GPIO_PIN_14, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_14, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    /* SPI1 CS: PD14 */
    LL_GPIO_SetPinMode(GPIOD, LL_GPIO_PIN_14, LL_GPIO_MODE_OUTPUT);
    LL_GPIO_SetPinSpeed(GPIOD, LL_GPIO_PIN_14, LL_GPIO_SPEED_FREQ_VERY_HIGH);
    LL_GPIO_SetPinOutputType(GPIOD, LL_GPIO_PIN_14, LL_GPIO_OUTPUT_PUSHPULL);
    LL_GPIO_SetPinPull(GPIOD, LL_GPIO_PIN_14, LL_GPIO_PULL_UP); //or modf persists even tho we are using software nss.
    LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);

    /* SAI1 GPIO: PE2 (MCLK), PE4 (FS), PE5 (SCK), PE6 (SD_A), PE3 (SD_B) */
    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_2, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_2, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_3, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_3, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_3, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_4, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_4, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_4, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_5, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_5, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_5, LL_GPIO_SPEED_FREQ_VERY_HIGH);

    LL_GPIO_SetPinMode(GPIOE, LL_GPIO_PIN_6, LL_GPIO_MODE_ALTERNATE);
    LL_GPIO_SetAFPin_0_7(GPIOE, LL_GPIO_PIN_6, LL_GPIO_AF_6);
    LL_GPIO_SetPinSpeed(GPIOE, LL_GPIO_PIN_6, LL_GPIO_SPEED_FREQ_VERY_HIGH);
}

void SystemClock_Config(void) {
    LL_FLASH_SetLatency(LL_FLASH_LATENCY_4);
    while(LL_FLASH_GetLatency() != LL_FLASH_LATENCY_4);

    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
    while (LL_PWR_IsActiveFlag_VOS() == 0);
    // ALSO wait for VOS0 ready in D3CR (H723 RevZ requirement)
    while ((PWR->D3CR & PWR_D3CR_VOSRDY) == 0);

    /* Enable HSE */
    LL_RCC_HSE_Enable();
    while(LL_RCC_HSE_IsReady() != 1);

    /* PLL1 Configuration for System Clock and 98.304MHz PLL1Q */
    /* HSE = 25MHz.
       M = 5 -> 5MHz input to PLL.
       N = 98.304 -> VCO = 5 * 98.304 = 491.52 MHz.
       P = 1 -> CPU = 491.52 MHz (H723 limit is 550MHz).
       Q = 5 -> PLL1Q = 491.52 / 5 = 98.304 MHz.
       FRACN = 0.304 * 8192 = 2490.
    */
    LL_RCC_PLL_SetSource(LL_RCC_PLLSOURCE_HSE);

    LL_RCC_PLL1_SetM(5);
    LL_RCC_PLL1_SetN(98);
    LL_RCC_PLL1_SetFRACN(2490);
    LL_RCC_PLL1FRACN_Enable();

    LL_RCC_PLL1_SetP(1);
    LL_RCC_PLL1_SetQ(5);
    LL_RCC_PLL1_SetR(2);

    LL_RCC_PLL1_SetVCOInputRange(LL_RCC_PLLINPUTRANGE_2_4);
    LL_RCC_PLL1_SetVCOOutputRange(LL_RCC_PLLVCORANGE_WIDE);

    LL_RCC_PLL1_Enable();
    while(LL_RCC_PLL1_IsReady() != 1);

    LL_RCC_PLL1P_Enable();
    LL_RCC_PLL1Q_Enable();

    /* Set Sysclk to PLL1P */
    LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL1);
    while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL1);

    LL_RCC_SetAHBPrescaler(LL_RCC_AHB_DIV_2);
    LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_2);
    LL_RCC_SetAPB2Prescaler(LL_RCC_APB2_DIV_2);
    LL_RCC_SetAPB3Prescaler(LL_RCC_APB3_DIV_2);
    LL_RCC_SetAPB4Prescaler(LL_RCC_APB4_DIV_2);

    // kernel clock source first
    RCC->D2CCIP1R &= ~RCC_D2CCIP1R_SPI45SEL; //0b000 =apb2
    RCC->D2CCIP1R |= (0x3 << RCC_D2CCIP1R_SPI45SEL_Pos);  // HSE
    __NOP();
    RCC->APB2ENR |= RCC_APB2ENR_SPI4EN;
    __NOP();
    (void)RCC->APB2ENR;  // dummy read to ensure clock is active

    // verify immediately
    if (!(RCC->APB2ENR & RCC_APB2ENR_SPI4EN)) {
        // trap here if still not set
        while(1);
    }
}






static void mySimpleWrite(void){
    // // CS low
    LL_GPIO_ResetOutputPin(GPIOD, LL_GPIO_PIN_14);
    // write both bytes
    while (!(SPI4->SR & SPI_SR_TXP));
    *(volatile uint8_t *)&SPI4->TXDR = 0xAA;
    while (!(SPI4->SR & SPI_SR_TXP));
    *(volatile uint8_t *)&SPI4->TXDR = 0x55;
    // start
    SPI4->CR1 |= SPI_CR1_CSTART;
    __DSB();
    __NOP();
    //CS high
    LL_GPIO_SetOutputPin(GPIOD, LL_GPIO_PIN_14);
}

void Error_Handler(void) {
    while (1);
}